# Reference: https://docs.readthedocs.io/en/latest/yaml-config.html

build:
  image: latest

# Possible options: htmlzip, pdf, epub
# Disable (single) htmlzip as it's way too big to be useful,
# and leads to excessive memory usage on build
# Disable pdf as it generates too many latex warnings and the build
# is killed once logs reach 4 MB.
formats:
  - epub
