os: linux
dist: bionic
language: python - "3.8"

env:
  global:
    - SPHINX_NO_GDSCRIPT=1
    - SPHINX_NO_SEARCH=1
    - SPHINX_NO_DESCRIPTIONS=1

matrix:
  include:
    - name: Static checks (format.sh) + Sphinx build
      stage: build
      os: linux
      addons:
        apt:
          packages:
            - dos2unix
            - recode

install:
  - pip install -r requirements.txt
  - pip install codespell

script:
  - bash _tools/format.sh

  # Check for possible typos
  - codespell -I _tools/codespell-ignore.txt {about,community,development,getting_started,tutorials}/**/*.rst

  # TODO: Add `-W` to turn warnings into errors.
  # This can only be done once all warnings have been fixed.
  - sphinx-build --color -b dummy -d _build/doctrees . _build/html
