name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint and build documentation
        run: |
          # Install tools used by `_tools/format.sh`.
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix recode
          # Append the `PATH` so we can run `codespell`.
          export PATH="$HOME/.local/bin:$PATH"
          pip3 install -r requirements.txt
          pip3 install codespell
          bash _tools/format.sh
          codespell -I _tools/codespell-ignore.txt {about,community,development,getting_started,tutorials}/**/*.rst
          # Use dummy builder to improve performance.
          sphinx-build --color -b dummy -d _build/doctrees . _build/html
